views.area.views_extend_result:
  type: views_area
  label: 'Views Extend Result'
  mapping:
    content:
      type: text
      label: 'The shown text of the result summary area'
views.area.views_extend_text:
  type: views_area
  label: 'Views Extend Text'
  mapping:
    content:
      type: text
      label: 'The shown text of the result summary area'
